apiVersion: v1
kind: Namespace
metadata:
  name:  hi

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pods-low
  namespace: hi
spec:
  hard:
    cpu: "0.5"
    memory: 4Gi
  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: hi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "1000m"
          requests:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp2
  namespace: hi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      containers:
      - name: myapp2
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "1000m"
          requests:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: hi
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80

